sudo: required
services:
    - docker

before_install:
    - docker build -t alexkolomiytsev/learn-docker-client-dev -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true alexkolomiytsev/learn-docker-client-dev npm run test

after_success:
    - docker build -t alexkolomiytsev/learn-docker-client ./client
    - docker build -t alexkolomiytsev/learn-docker-nginx ./nginx
    - docker build -t alexkolomiytsev/learn-docker-server ./server
    - docker build -t alexkolomiytsev/learn-docker-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push alexkolomiytsev/learn-docker-client
    - docker push alexkolomiytsev/learn-docker-nginx
    - docker push alexkolomiytsev/learn-docker-server
    - docker push alexkolomiytsev/learn-docker-worker 
