sudo: required
services:
    - docker

before_install:
    - docker build -t alexkolomiytsev/learn-docker-dev -f Dockerfile.dev .

script:
    - docker run -e CI=true alexkolomiytsev/learn-docker-dev npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "learn-docker"
    env: "LearnDocker-env"
    bucket-name: "elasticbeanstalk-us-east-2-889814516794"
    bucket_path: "learn-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

